{% set version = "0.8.1" %}
{% set name = "sagemath-db-elliptic-curves" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://files.sagemath.org/spkg/upstream/elliptic_curves/elliptic_curves-{{ version }}.tar.bz2
  sha256: 5fba5470d9d91f06282ed5edfc45bf0ea1c5f7c8d4837c46234b17be1481fd50

build:
  number: 1
  noarch: generic

requirements:
  build:
    - curl
    - sqlite
    - python

test:
  commands:
    - test -f $PREFIX/share/cremona/cremona_mini.db
    - test -f $PREFIX/share/ellcurves/rank0

about:
  home: https://github.com/sagemath/sage
  license: GPLv2+
  summary: |
    A small subset of the data in John Cremona's database of elliptic curves up
    to conductor 10000 and William Stein's database of interesting curves

extra:
  recipe-maintainers:
    - isuruf
