travis:
  secure:
    BINSTAR_TOKEN: KqndZY0SvMNlJubLlJZmI2F9twiNrQ3O5miH+aQ8XOOUsm0ePSxBMQPpCFBZVWLHuqSzmDvs42D/A+UF2v5mGHIOk0BXZse1wpOtwNqiai6IGsc+H9cpuzznUUwKufmgAC+fHznsygcFXCRzIPIJ62cQjL9/scRDKHNt09CvkLPgtjqVHH5te8ybLAIXjT4pnsqHE9vVoePCAocWtdJo+GLT3NJ5TwLEDC69Pru3tSECakgmb7MV8Uv8ck0sj/+g2VDph8nYiLzPVH+WmHYUYbgXMk3lqmJh62Va5H/0TeHT7CY/V3c3s/wmztEdCuGjENUfp3Z8Qb0+gu7uJcIyA/Pn2u1fDDsIf1iX0AlHhc/LF/h02XH70sKLG1OSGOnut5Z/zE9F6+WxnhnsVjaNgEgQSxkJfkVuZC6aUgQYsllyXHm67SS/IjjqqusGshygR6bIWP1JpmDCGQqnVxpeJ9e1qI45KADe9A5oMJ8wcVukRdUBqPmWq+3SMWhNvhmI/supNLSVllv87u9p20ocL6vEWBfqTH0kg1KXLIJqcY2nbH8iw4e0Dy3fP+sSHqG9bx2t97PetP7mE6N5Eupx4kJf9qy30pTAZOEB4kW9V671jcNOkzoA9uIDZrw9a/o8/wRytJQwn8syVD1IMSyUxmFnoDxeZ/HCJsPxP+9UlP8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
