appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: JTUvmRPTANnxcWzb/QudFDjaW04BDOw70mtLvE0b/+Yz5oNUpAPETPK+CMG8PYeBBuxgx2qESRJ7JUzSG6JJg3Jmm13pKB6XMrVeS2r+CpOezoI6YpeEMoC1H5YpO+J4YTXY2NjgYw34+PfB2bvuY18JwWUkyx+CSuwXv8rJbOGqBI1uVPDeLpMLpU/ai8DzIxKU5w8+DogShUs/qzeHnuij6XB81HibBMhIVrFiVDF53UWUddPFkLhpHKczb+2Js3hSvqItJB5ivKE2k7XwQb87KhlePOXdxCgipEyhb4INgsLwxKq6o4YKbHp9mE4S2pb9zZ9w3qmycuDD9+mySfRoor1zxoUyz9n8CGOs+A94fRFI+8LVZ/wJC+pWSqnNoEUOUwfuaLkTuAjiH/H2ZHfriRV5C3fCEWkzls7GVKEz3oXqLq0VmirrA+g3LWbuRIXtCKDVIVzsX3NamoaOkNJX/6kAbhagd/lN503enOYTHgoyH+UU8fC06zQb0i//FjkumLMtBmp3e6OR+ywXgsTf5nYwWgITbze8raRXHLv2UuVGJCCC4zVth/9M3s7oWY6vQFe1xktlUMRk5KnZm1Pe2FrjlI1qqabwzriCQ8eUiRAAkA1Ky4DcM8H4edTfgw+tPeMh5rjyStlhKPnjohyfYLSjRpM9ppTWko1yA7M=}
conda_forge_output_validation: true
